name: Unraid Flash Backup

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:

jobs:
  backup:
    runs-on:  self-hosted 

    env:
      USERNAME: ${{ secrets.UNRAID_USERNAME }}
      PASSWORD: ${{ secrets.UNRAID_PASSWORD }}
      HUB_URL: http://192.168.1.101:4444/wd/hub
      WEB_URL: http://192.168.1.101

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
      - name: Run Backup
        run: python backup.py
